import fs from "fs";
import path from "path";
import { hardhatArguments } from "hardhat";

/**
 * @notice Updates the frontend with the deployed Don and Donation contract addresses
 * This script is called by the deployDonationSystem.ts script after deployment
 * It updates only the Don and Donation addresses in the existing frontend file
 * It also copies the ABI and bytecode files to the frontend
 * @param donAddress The address of the deployed DON token
 * @param donationAddress The address of the deployed Donation contract
 */
export async function updateFrontendAddresses(
  donAddress: string,
  donationAddress: string
): Promise<void> {
  console.log("\nUpdating frontend with deployed contract addresses...");

  // Get the network name
  const network = hardhatArguments.network || "localhost";
  
  // Define the path for the server utility file
  const frontendDir = path.join(__dirname, "../../poscidondao_frontend");
  const serverUtilPath = path.join(frontendDir, "src/app/utils/serverConfig.ts");
  
  // Define paths for ABI and bytecode directories
  const frontendAbiDir = path.join(frontendDir, "src/app/abi");
  const frontendBytecodeDir = path.join(frontendDir, "src/app/abi/bytecode");
  
  // Check if the frontend directory exists
  if (!fs.existsSync(frontendDir)) {
    console.log(`Frontend directory not found at ${frontendDir}`);
    console.log("Skipping frontend update. Please update the frontend manually.");
    return;
  }
  
  // Check if the server config file exists
  if (!fs.existsSync(serverUtilPath)) {
    console.log(`Server config file not found at ${serverUtilPath}`);
    console.log("Creating a new server config file with only Don and Donation addresses.");
    
    // Create a basic server config file with only Don and Donation addresses
    const basicServerConfig = `'use server';

// This file is auto-generated by the deployDonationSystem script
// Last updated: ${new Date().toISOString()}
// Network: ${network}

const ALCHEMY_KEY = process.env.ALCHEMY_KEY_PROTOCOL ?? '';
const PRIVATE_KEY = process.env.PRIVATE_KEY ?? '';

export async function getRpcUrl() {
  return \`https://base-sepolia.g.alchemy.com/v2/\${ALCHEMY_KEY}\`;
};

export async function getPrivateKey() {
  return PRIVATE_KEY;
};

export async function getNetworkInfo() {
  const rpcUrl = await getRpcUrl();
  return {
    chainId: ${network === "base-sepolia" ? "84532" : "8453"},
    providerUrl: \`\${rpcUrl}\`,
    explorerLink: '${network === "base-sepolia" ? "https://sepolia.basescan.org" : "https://basescan.org"}',
    don: '${donAddress}',
    donation: '${donationAddress}',
  };
};
`;
    
    // Create directory if it doesn't exist
    const serverUtilsDir = path.dirname(serverUtilPath);
    if (!fs.existsSync(serverUtilsDir)) {
      fs.mkdirSync(serverUtilsDir, { recursive: true });
    }
    
    // Write the basic server config file
    fs.writeFileSync(serverUtilPath, basicServerConfig);
    console.log(`Created new server config file at: ${serverUtilPath}`);
  } else {
    // Read the existing server config file
    console.log(`Reading existing server config file from: ${serverUtilPath}`);
    let serverConfigContent = fs.readFileSync(serverUtilPath, 'utf8');
    
    // Add a comment to indicate the file was updated
    const updateComment = `// Updated by deployDonationSystem script on ${new Date().toISOString()}`;
    if (!serverConfigContent.includes('// Updated by deployDonationSystem')) {
      // Add the comment after the first line (which should be 'use server')
      const lines = serverConfigContent.split('\n');
      lines.splice(1, 0, updateComment);
      serverConfigContent = lines.join('\n');
    } else {
      // Replace the existing update comment
      serverConfigContent = serverConfigContent.replace(
        /\/\/ Updated by deployDonationSystem script on .*/,
        updateComment
      );
    }
    
    // Update the Don and Donation addresses
    // We need to handle different possible formats in the existing file
    
    // Update don address
    const donRegex = /(don\s*:\s*['"])([^'"]*)(["'])/;
    if (donRegex.test(serverConfigContent)) {
      serverConfigContent = serverConfigContent.replace(donRegex, `$1${donAddress}$3`);
    } else {
      console.log("Could not find don address in the server config file.");
      console.log("Please update the don address manually.");
    }
    
    // Update donation address
    const donationRegex = /(donation\s*:\s*['"])([^'"]*)(["'])/;
    if (donationRegex.test(serverConfigContent)) {
      serverConfigContent = serverConfigContent.replace(donationRegex, `$1${donationAddress}$3`);
    } else {
      console.log("Could not find donation address in the server config file.");
      console.log("Please update the donation address manually.");
    }
    
    // Write the updated server config file
    fs.writeFileSync(serverUtilPath, serverConfigContent);
    console.log(`Updated server config file at: ${serverUtilPath}`);
    console.log(`- Don address updated to: ${donAddress}`);
    console.log(`- Donation address updated to: ${donationAddress}`);
  }
  
  // Copy ABI and bytecode files to the frontend
  console.log("\nCopying ABI and bytecode files to the frontend...");
  
  // Create ABI and bytecode directories if they don't exist
  if (!fs.existsSync(frontendAbiDir)) {
    fs.mkdirSync(frontendAbiDir, { recursive: true });
    console.log(`Created ABI directory at: ${frontendAbiDir}`);
  }
  
  if (!fs.existsSync(frontendBytecodeDir)) {
    fs.mkdirSync(frontendBytecodeDir, { recursive: true });
    console.log(`Created bytecode directory at: ${frontendBytecodeDir}`);
  }
  
  // Define paths for contract artifacts
  const donArtifactPath = path.join(__dirname, "../artifacts/contracts/tokens/Don.sol/Don.json");
  const donationArtifactPath = path.join(__dirname, "../artifacts/contracts/donating/Donation.sol/Donation.json");
  
  // Check if artifact files exist
  if (!fs.existsSync(donArtifactPath)) {
    console.log(`Don artifact not found at: ${donArtifactPath}`);
    console.log("Please compile the contracts first.");
  } else {
    try {
      // Read the Don artifact
      const donArtifact = JSON.parse(fs.readFileSync(donArtifactPath, 'utf8'));
      
      // Extract ABI and bytecode
      const donAbi = JSON.stringify(donArtifact.abi, null, 2);
      const donBytecode = JSON.stringify({ bytecode: donArtifact.bytecode }, null, 2);
      
      // Write ABI and bytecode files
      fs.writeFileSync(path.join(frontendAbiDir, "Don.json"), donAbi);
      fs.writeFileSync(path.join(frontendBytecodeDir, "Don.json"), donBytecode);
      
      console.log(`Copied Don ABI and bytecode to frontend`);
    } catch (error) {
      console.error(`Error copying Don ABI and bytecode:`, error);
    }
  }
  
  // Check if Donation artifact file exists
  if (!fs.existsSync(donationArtifactPath)) {
    console.log(`Donation artifact not found at: ${donationArtifactPath}`);
    console.log("Please compile the contracts first.");
  } else {
    try {
      // Read the Donation artifact
      const donationArtifact = JSON.parse(fs.readFileSync(donationArtifactPath, 'utf8'));
      
      // Extract ABI and bytecode
      const donationAbi = JSON.stringify(donationArtifact.abi, null, 2);
      const donationBytecode = JSON.stringify({ bytecode: donationArtifact.bytecode }, null, 2);
      
      // Write ABI and bytecode files
      fs.writeFileSync(path.join(frontendAbiDir, "Donation.json"), donationAbi);
      fs.writeFileSync(path.join(frontendBytecodeDir, "Donation.json"), donationBytecode);
      
      console.log(`Copied Donation ABI and bytecode to frontend`);
    } catch (error) {
      console.error(`Error copying Donation ABI and bytecode:`, error);
    }
  }
  
  console.log("\nFrontend update completed successfully!");
} 